#define TRUE 1
#define FALSE 0

#define SCREEN_WIDTH 426
#define SCREEN_HEIGHT 240
#define TILE_SIZE 10

#define TILES_X (SCREEN_WIDTH / TILE_SIZE)
#define TILES_Y (SCREEN_HEIGHT / TILE_SIZE)

#define FPS 60
#define FRAME_TARGET_TIME (1000 / FPS)